// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// App Engine Routing.
///
/// Defines routing characteristics specific to App Engine - service, version,
/// and instance.
///
/// For more information about services, versions, and instances see
/// [An Overview of App
/// Engine](https://cloud.google.com/appengine/docs/python/an-overview-of-app-engine),
/// [Microservices Architecture on Google App
/// Engine](https://cloud.google.com/appengine/docs/python/microservices-on-app-engine),
/// [App Engine Standard request
/// routing](https://cloud.google.com/appengine/docs/standard/python/how-requests-are-routed),
/// and [App Engine Flex request
/// routing](https://cloud.google.com/appengine/docs/flexible/python/how-requests-are-routed).
///
/// Using [AppEngineRouting][google.cloud.tasks.v2.AppEngineRouting] requires
/// [`appengine.applications.get`](https://cloud.google.com/appengine/docs/admin-api/access-control)
/// Google IAM permission for the project
/// and the following scope:
///
/// `https://www.googleapis.com/auth/cloud-platform`
///
/// [google.cloud.tasks.v2.AppEngineRouting]: <doc:AppEngineRouting>
public struct AppEngineRouting: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// App service.
  ///
  /// By default, the task is sent to the service which is the default
  /// service when the task is attempted.
  ///
  /// For some queues or tasks which were created using the App Engine
  /// Task Queue API, [host][google.cloud.tasks.v2.AppEngineRouting.host] is not
  /// parsable into [service][google.cloud.tasks.v2.AppEngineRouting.service],
  /// [version][google.cloud.tasks.v2.AppEngineRouting.version], and
  /// [instance][google.cloud.tasks.v2.AppEngineRouting.instance]. For example,
  /// some tasks which were created using the App Engine SDK use a custom domain
  /// name; custom domains are not parsed by Cloud Tasks. If
  /// [host][google.cloud.tasks.v2.AppEngineRouting.host] is not parsable, then
  /// [service][google.cloud.tasks.v2.AppEngineRouting.service],
  /// [version][google.cloud.tasks.v2.AppEngineRouting.version], and
  /// [instance][google.cloud.tasks.v2.AppEngineRouting.instance] are the empty
  /// string.
  ///
  /// [google.cloud.tasks.v2.AppEngineRouting.host]: <doc:AppEngineRouting/host>
  /// [google.cloud.tasks.v2.AppEngineRouting.instance]: <doc:AppEngineRouting/instance>
  /// [google.cloud.tasks.v2.AppEngineRouting.service]: <doc:AppEngineRouting/service>
  /// [google.cloud.tasks.v2.AppEngineRouting.version]: <doc:AppEngineRouting/version>
  public var service: Swift.String = Swift.String()

  /// App version.
  ///
  /// By default, the task is sent to the version which is the default
  /// version when the task is attempted.
  ///
  /// For some queues or tasks which were created using the App Engine
  /// Task Queue API, [host][google.cloud.tasks.v2.AppEngineRouting.host] is not
  /// parsable into [service][google.cloud.tasks.v2.AppEngineRouting.service],
  /// [version][google.cloud.tasks.v2.AppEngineRouting.version], and
  /// [instance][google.cloud.tasks.v2.AppEngineRouting.instance]. For example,
  /// some tasks which were created using the App Engine SDK use a custom domain
  /// name; custom domains are not parsed by Cloud Tasks. If
  /// [host][google.cloud.tasks.v2.AppEngineRouting.host] is not parsable, then
  /// [service][google.cloud.tasks.v2.AppEngineRouting.service],
  /// [version][google.cloud.tasks.v2.AppEngineRouting.version], and
  /// [instance][google.cloud.tasks.v2.AppEngineRouting.instance] are the empty
  /// string.
  ///
  /// [google.cloud.tasks.v2.AppEngineRouting.host]: <doc:AppEngineRouting/host>
  /// [google.cloud.tasks.v2.AppEngineRouting.instance]: <doc:AppEngineRouting/instance>
  /// [google.cloud.tasks.v2.AppEngineRouting.service]: <doc:AppEngineRouting/service>
  /// [google.cloud.tasks.v2.AppEngineRouting.version]: <doc:AppEngineRouting/version>
  public var version: Swift.String = Swift.String()

  /// App instance.
  ///
  /// By default, the task is sent to an instance which is available when
  /// the task is attempted.
  ///
  /// Requests can only be sent to a specific instance if
  /// [manual scaling is used in App Engine
  /// Standard](https://cloud.google.com/appengine/docs/python/an-overview-of-app-engine?hl=en_US#scaling_types_and_instance_classes).
  /// App Engine Flex does not support instances. For more information, see
  /// [App Engine Standard request
  /// routing](https://cloud.google.com/appengine/docs/standard/python/how-requests-are-routed)
  /// and [App Engine Flex request
  /// routing](https://cloud.google.com/appengine/docs/flexible/python/how-requests-are-routed).
  public var instance: Swift.String = Swift.String()

  /// Output only. The host that the task is sent to.
  ///
  /// The host is constructed from the domain name of the app associated with
  /// the queue's project ID (for example <app-id>.appspot.com), and the
  /// [service][google.cloud.tasks.v2.AppEngineRouting.service],
  /// [version][google.cloud.tasks.v2.AppEngineRouting.version], and
  /// [instance][google.cloud.tasks.v2.AppEngineRouting.instance]. Tasks which
  /// were created using the App Engine SDK might have a custom domain name.
  ///
  /// For more information, see
  /// [How Requests are
  /// Routed](https://cloud.google.com/appengine/docs/standard/python/how-requests-are-routed).
  ///
  /// [google.cloud.tasks.v2.AppEngineRouting.instance]: <doc:AppEngineRouting/instance>
  /// [google.cloud.tasks.v2.AppEngineRouting.service]: <doc:AppEngineRouting/service>
  /// [google.cloud.tasks.v2.AppEngineRouting.version]: <doc:AppEngineRouting/version>
  public var host: Swift.String = Swift.String()

  /// Initialize a new instance of `AppEngineRouting`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AppEngineRouting().with { $0.service = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.AppEngineRouting"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
