// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The status of a task attempt.
public struct Attempt: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The time that this attempt was scheduled.
  ///
  /// `schedule_time` will be truncated to the nearest microsecond.
  public var scheduleTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time that this attempt was dispatched.
  ///
  /// `dispatch_time` will be truncated to the nearest microsecond.
  public var dispatchTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time that this attempt response was received.
  ///
  /// `response_time` will be truncated to the nearest microsecond.
  public var responseTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The response from the worker for this attempt.
  ///
  /// If `response_time` is unset, then the task has not been attempted or is
  /// currently running and the `response_status` field is meaningless.
  public var responseStatus: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Attempt`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attempt().with { $0.scheduleTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scheduleTime = CodingKeys(stringValue: "scheduleTime")
    static let dispatchTime = CodingKeys(stringValue: "dispatchTime")
    static let responseTime = CodingKeys(stringValue: "responseTime")
    static let responseStatus = CodingKeys(stringValue: "responseStatus")

    static let _knownKeys: Set<Swift.String> = [
      "scheduleTime",
      "dispatchTime",
      "responseTime",
      "responseStatus",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scheduleTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .scheduleTime)
    self.dispatchTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .dispatchTime)
    self.responseTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .responseTime)
    self.responseStatus = try container.decodeIfPresent(
      GoogleRpc.Status.self, forKey: .responseStatus)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.scheduleTime, forKey: .scheduleTime)
    try container.encodeIfPresent(self.dispatchTime, forKey: .dispatchTime)
    try container.encodeIfPresent(self.responseTime, forKey: .responseTime)
    try container.encodeIfPresent(self.responseStatus, forKey: .responseStatus)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.Attempt"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
