// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleIAMV1
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CloudTasksLogging: CloudTasksStub {
    let inner: any CloudTasksStub
    let logger: Logger

    public init(_ inner: any CloudTasksStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-tasks-v2"
      logger[metadataKey: "gcp.client.service"] = "cloudtasks"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CloudTasks"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listQueues(
      request: ListQueuesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.ListQueuesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listQueues",
        action: {
          (r: ListQueuesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.ListQueuesResponse
          in
          return try await self.inner.listQueues(request: r, options: o)
        })
    }

    public func getQueue(
      request: GetQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        name: "getQueue",
        action: {
          (r: GetQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.getQueue(request: r, options: o)
        })
    }

    public func createQueue(
      request: CreateQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        name: "createQueue",
        action: {
          (r: CreateQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.createQueue(request: r, options: o)
        })
    }

    public func updateQueue(
      request: UpdateQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateQueue",
        action: {
          (r: UpdateQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.updateQueue(request: r, options: o)
        })
    }

    public func deleteQueue(
      request: DeleteQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteQueue",
        action: { (r: DeleteQueueRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteQueue(request: r, options: o)
        })
    }

    public func purgeQueue(
      request: PurgeQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        name: "purgeQueue",
        action: {
          (r: PurgeQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.purgeQueue(request: r, options: o)
        })
    }

    public func pauseQueue(
      request: PauseQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        name: "pauseQueue",
        action: {
          (r: PauseQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.pauseQueue(request: r, options: o)
        })
    }

    public func resumeQueue(
      request: ResumeQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeQueue",
        action: {
          (r: ResumeQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.resumeQueue(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listTasks(
      request: ListTasksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.ListTasksResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTasks",
        action: {
          (r: ListTasksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.ListTasksResponse
          in
          return try await self.inner.listTasks(request: r, options: o)
        })
    }

    public func getTask(
      request: GetTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTask",
        action: {
          (r: GetTaskRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Task
          in
          return try await self.inner.getTask(request: r, options: o)
        })
    }

    public func createTask(
      request: CreateTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTask",
        action: {
          (r: CreateTaskRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Task
          in
          return try await self.inner.createTask(request: r, options: o)
        })
    }

    public func deleteTask(
      request: DeleteTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTask",
        action: { (r: DeleteTaskRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTask(request: r, options: o)
        })
    }

    public func runTask(
      request: RunTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task {
      try await self._intercept(
        request: request,
        options: options,
        name: "runTask",
        action: {
          (r: RunTaskRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Task
          in
          return try await self.inner.runTask(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
