// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class CloudTasksRetry: CloudTasksStub {
    let inner: any CloudTasksStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any CloudTasksStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listQueues(
      request: ListQueuesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.ListQueuesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListQueuesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.ListQueuesResponse
          in
          return try await self.inner.listQueues(request: r, options: o)
        })
    }

    public func getQueue(
      request: GetQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.getQueue(request: r, options: o)
        })
    }

    public func createQueue(
      request: CreateQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.createQueue(request: r, options: o)
        })
    }

    public func updateQueue(
      request: UpdateQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.updateQueue(request: r, options: o)
        })
    }

    public func deleteQueue(
      request: DeleteQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteQueueRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteQueue(request: r, options: o)
        })
    }

    public func purgeQueue(
      request: PurgeQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PurgeQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.purgeQueue(request: r, options: o)
        })
    }

    public func pauseQueue(
      request: PauseQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PauseQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.pauseQueue(request: r, options: o)
        })
    }

    public func resumeQueue(
      request: ResumeQueueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResumeQueueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Queue
          in
          return try await self.inner.resumeQueue(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listTasks(
      request: ListTasksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.ListTasksResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTasksRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.ListTasksResponse
          in
          return try await self.inner.listTasks(request: r, options: o)
        })
    }

    public func getTask(
      request: GetTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTaskRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Task
          in
          return try await self.inner.getTask(request: r, options: o)
        })
    }

    public func createTask(
      request: CreateTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTaskRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Task
          in
          return try await self.inner.createTask(request: r, options: o)
        })
    }

    public func deleteTask(
      request: DeleteTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteTaskRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTask(request: r, options: o)
        })
    }

    public func runTask(
      request: RunTaskRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RunTaskRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTasksV2.Task
          in
          return try await self.inner.runTask(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
