// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleWKT
import GoogleGax

extension Clients {
  protocol CloudTasksStub: Sendable {
    func listQueues(
      request: ListQueuesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.ListQueuesResponse

    func getQueue(
      request: GetQueueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue

    func createQueue(
      request: CreateQueueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue

    func updateQueue(
      request: UpdateQueueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue

    func deleteQueue(
      request: DeleteQueueRequest, options: GoogleGax.RequestOptions
    ) async throws

    func purgeQueue(
      request: PurgeQueueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue

    func pauseQueue(
      request: PauseQueueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue

    func resumeQueue(
      request: ResumeQueueRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Queue

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listTasks(
      request: ListTasksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.ListTasksResponse

    func getTask(
      request: GetTaskRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task

    func createTask(
      request: CreateTaskRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task

    func deleteTask(
      request: DeleteTaskRequest, options: GoogleGax.RequestOptions
    ) async throws

    func runTask(
      request: RunTaskRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTasksV2.Task

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
