// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [CreateTask][google.cloud.tasks.v2.CloudTasks.CreateTask].
///
/// [google.cloud.tasks.v2.CloudTasks.CreateTask]: <doc:CloudTasksClient/createTask(request:options:)>
public struct CreateTaskRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The queue name. For example:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID`
  ///
  /// The queue must already exist.
  public var parent: Swift.String = Swift.String()

  /// Required. The task to add.
  ///
  /// Task names have the following format:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID/tasks/TASK_ID`.
  /// The user can optionally specify a task
  /// [name][google.cloud.tasks.v2.Task.name]. If a name is not specified then
  /// the system will generate a random unique task id, which will be set in the
  /// task returned in the [response][google.cloud.tasks.v2.Task.name].
  ///
  /// If [schedule_time][google.cloud.tasks.v2.Task.schedule_time] is not set or
  /// is in the past then Cloud Tasks will set it to the current time.
  ///
  /// Task De-duplication:
  ///
  /// Explicitly specifying a task ID enables task de-duplication.  If
  /// a task's ID is identical to that of an existing task or a task
  /// that was deleted or executed recently then the call will fail
  /// with [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS].
  /// If the task's queue was created using Cloud Tasks, then another task with
  /// the same name can't be created for ~1hour after the original task was
  /// deleted or executed. If the task's queue was created using queue.yaml or
  /// queue.xml, then another task with the same name can't be created
  /// for ~9days after the original task was deleted or executed.
  ///
  /// Because there is an extra lookup cost to identify duplicate task
  /// names, these [CreateTask][google.cloud.tasks.v2.CloudTasks.CreateTask]
  /// calls have significantly increased latency. Using hashed strings for the
  /// task id or for the prefix of the task id is recommended. Choosing task ids
  /// that are sequential or have sequential prefixes, for example using a
  /// timestamp, causes an increase in latency and error rates in all
  /// task commands. The infrastructure relies on an approximately
  /// uniform distribution of task ids to store and serve tasks
  /// efficiently.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.CreateTask]: <doc:CloudTasksClient/createTask(request:options:)>
  /// [google.cloud.tasks.v2.Task.name]: <doc:Task/name>
  /// [google.cloud.tasks.v2.Task.schedule_time]: <doc:Task/scheduleTime>
  public var task: Task? = nil

  /// The response_view specifies which subset of the
  /// [Task][google.cloud.tasks.v2.Task] will be returned.
  ///
  /// By default response_view is [BASIC][google.cloud.tasks.v2.Task.View.BASIC];
  /// not all information is retrieved by default because some data, such as
  /// payloads, might be desirable to return only when needed because
  /// of its large size or because of the sensitivity of data that it
  /// contains.
  ///
  /// Authorization for [FULL][google.cloud.tasks.v2.Task.View.FULL] requires
  /// `cloudtasks.tasks.fullView` [Google IAM](https://cloud.google.com/iam/)
  /// permission on the [Task][google.cloud.tasks.v2.Task] resource.
  ///
  /// [google.cloud.tasks.v2.Task]: <doc:Task>
  /// [google.cloud.tasks.v2.Task.View.BASIC]: <doc:Task/View/basic>
  /// [google.cloud.tasks.v2.Task.View.FULL]: <doc:Task/View/full>
  public var responseView: Task.View = Task.View()

  /// Initialize a new instance of `CreateTaskRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateTaskRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.CreateTaskRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
