// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [CreateTask][google.cloud.tasks.v2.CloudTasks.CreateTask].
///
/// [google.cloud.tasks.v2.CloudTasks.CreateTask]: <doc:CloudTasksClient/createTask(request:options:)>
public struct CreateTaskRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The queue name. For example:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID`
  ///
  /// The queue must already exist.
  public var parent: Swift.String = Swift.String()

  /// Required. The task to add.
  ///
  /// Task names have the following format:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID/tasks/TASK_ID`.
  /// The user can optionally specify a task
  /// [name][google.cloud.tasks.v2.Task.name]. If a name is not specified then
  /// the system will generate a random unique task id, which will be set in the
  /// task returned in the [response][google.cloud.tasks.v2.Task.name].
  ///
  /// If [schedule_time][google.cloud.tasks.v2.Task.schedule_time] is not set or
  /// is in the past then Cloud Tasks will set it to the current time.
  ///
  /// Task De-duplication:
  ///
  /// Explicitly specifying a task ID enables task de-duplication.  If
  /// a task's ID is identical to that of an existing task or a task
  /// that was deleted or executed recently then the call will fail
  /// with [ALREADY_EXISTS][google.rpc.Code.ALREADY_EXISTS].
  /// If the task's queue was created using Cloud Tasks, then another task with
  /// the same name can't be created for ~1hour after the original task was
  /// deleted or executed. If the task's queue was created using queue.yaml or
  /// queue.xml, then another task with the same name can't be created
  /// for ~9days after the original task was deleted or executed.
  ///
  /// Because there is an extra lookup cost to identify duplicate task
  /// names, these [CreateTask][google.cloud.tasks.v2.CloudTasks.CreateTask]
  /// calls have significantly increased latency. Using hashed strings for the
  /// task id or for the prefix of the task id is recommended. Choosing task ids
  /// that are sequential or have sequential prefixes, for example using a
  /// timestamp, causes an increase in latency and error rates in all
  /// task commands. The infrastructure relies on an approximately
  /// uniform distribution of task ids to store and serve tasks
  /// efficiently.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.CreateTask]: <doc:CloudTasksClient/createTask(request:options:)>
  /// [google.cloud.tasks.v2.Task.name]: <doc:Task/name>
  /// [google.cloud.tasks.v2.Task.schedule_time]: <doc:Task/scheduleTime>
  public var task: Task? = nil

  /// The response_view specifies which subset of the
  /// [Task][google.cloud.tasks.v2.Task] will be returned.
  ///
  /// By default response_view is [BASIC][google.cloud.tasks.v2.Task.View.BASIC];
  /// not all information is retrieved by default because some data, such as
  /// payloads, might be desirable to return only when needed because
  /// of its large size or because of the sensitivity of data that it
  /// contains.
  ///
  /// Authorization for [FULL][google.cloud.tasks.v2.Task.View.FULL] requires
  /// `cloudtasks.tasks.fullView` [Google IAM](https://cloud.google.com/iam/)
  /// permission on the [Task][google.cloud.tasks.v2.Task] resource.
  ///
  /// [google.cloud.tasks.v2.Task]: <doc:Task>
  /// [google.cloud.tasks.v2.Task.View.BASIC]: <doc:Task/View/basic>
  /// [google.cloud.tasks.v2.Task.View.FULL]: <doc:Task/View/full>
  public var responseView: Task.View = Task.View()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateTaskRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateTaskRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let task = CodingKeys(stringValue: "task")
    static let responseView = CodingKeys(stringValue: "responseView")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "task",
      "responseView",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.task = try container.decodeIfPresent(Task.self, forKey: .task)
    if let value = try container.decodeIfPresent(Task.View.self, forKey: .responseView) {
      self.responseView = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.task, forKey: .task)
    try container.encode(self.responseView, forKey: .responseView)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.CreateTaskRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
