// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// HTTP request.
///
/// The task will be pushed to the worker as an HTTP request. If the worker
/// or the redirected worker acknowledges the task by returning a successful HTTP
/// response code ([`200` - `299`]), the task will be removed from the queue. If
/// any other HTTP response code is returned or no response is received, the
/// task will be retried according to the following:
///
/// * User-specified throttling: [retry
/// configuration][google.cloud.tasks.v2.Queue.retry_config],
///   [rate limits][google.cloud.tasks.v2.Queue.rate_limits], and the [queue's
///   state][google.cloud.tasks.v2.Queue.state].
///
/// * System throttling: To prevent the worker from overloading, Cloud Tasks may
///   temporarily reduce the queue's effective rate. User-specified settings
///   will not be changed.
///
///  System throttling happens because:
///
///   * Cloud Tasks backs off on all errors. Normally the backoff specified in
///     [rate limits][google.cloud.tasks.v2.Queue.rate_limits] will be used. But
///     if the worker returns `429` (Too Many Requests), `503` (Service
///     Unavailable), or the rate of errors is high, Cloud Tasks will use a
///     higher backoff rate. The retry specified in the `Retry-After` HTTP
///     response header is considered.
///
///   * To prevent traffic spikes and to smooth sudden increases in traffic,
///     dispatches ramp up slowly when the queue is newly created or idle and
///     if large numbers of tasks suddenly become available to dispatch (due to
///     spikes in create task rates, the queue being unpaused, or many tasks
///     that are scheduled at the same time).
///
/// [google.cloud.tasks.v2.Queue.rate_limits]: <doc:Queue/rateLimits>
/// [google.cloud.tasks.v2.Queue.retry_config]: <doc:Queue/retryConfig>
/// [google.cloud.tasks.v2.Queue.state]: <doc:Queue/state>
public struct HttpRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The full url path that the request will be sent to.
  ///
  /// This string must begin with either "http://" or "https://". Some examples
  /// are: `http://acme.com` and `https://acme.com/sales:8080`. Cloud Tasks will
  /// encode some characters for safety and compatibility. The maximum allowed
  /// URL length is 2083 characters after encoding.
  ///
  /// The `Location` header response from a redirect response [`300` - `399`]
  /// may be followed. The redirect is not counted as a separate attempt.
  public var url: Swift.String = Swift.String()

  /// The HTTP method to use for the request. The default is POST.
  public var httpMethod: HttpMethod = HttpMethod()

  /// HTTP request headers.
  ///
  /// This map contains the header field names and values.
  /// Headers can be set when the
  /// [task is created][google.cloud.tasks.v2beta3.CloudTasks.CreateTask].
  ///
  /// These headers represent a subset of the headers that will accompany the
  /// task's HTTP request. Some HTTP request headers will be ignored or replaced.
  ///
  /// A partial list of headers that will be ignored or replaced is:
  ///
  /// * Host: This will be computed by Cloud Tasks and derived from
  ///   [HttpRequest.url][google.cloud.tasks.v2.HttpRequest.url].
  /// * Content-Length: This will be computed by Cloud Tasks.
  /// * User-Agent: This will be set to `"Google-Cloud-Tasks"`.
  /// * `X-Google-*`: Google use only.
  /// * `X-AppEngine-*`: Google use only.
  ///
  /// `Content-Type` won't be set by Cloud Tasks. You can explicitly set
  /// `Content-Type` to a media type when the
  ///  [task is created][google.cloud.tasks.v2beta3.CloudTasks.CreateTask].
  ///  For example, `Content-Type` can be set to `"application/octet-stream"` or
  ///  `"application/json"`.
  ///
  /// Headers which can have multiple values (according to RFC2616) can be
  /// specified using comma-separated values.
  ///
  /// The size of the headers must be less than 80KB.
  ///
  /// [google.cloud.tasks.v2.HttpRequest.url]: <doc:HttpRequest/url>
  public var headers: [Swift.String: Swift.String] = [:]

  /// HTTP request body.
  ///
  /// A request body is allowed only if the
  /// [HTTP method][google.cloud.tasks.v2.HttpRequest.http_method] is POST, PUT,
  /// or PATCH. It is an error to set body on a task with an incompatible
  /// [HttpMethod][google.cloud.tasks.v2.HttpMethod].
  ///
  /// [google.cloud.tasks.v2.HttpMethod]: <doc:HttpMethod>
  /// [google.cloud.tasks.v2.HttpRequest.http_method]: <doc:HttpRequest/httpMethod>
  public var body: Foundation.Data = Foundation.Data()

  /// The mode for generating an `Authorization` header for HTTP requests.
  ///
  /// If specified, all `Authorization` headers in the
  /// [HttpRequest.headers][google.cloud.tasks.v2.HttpRequest.headers] field will
  /// be overridden.
  ///
  /// [google.cloud.tasks.v2.HttpRequest.headers]: <doc:HttpRequest/headers>
  public var authorizationHeader: OneOf_AuthorizationHeader? = nil

  /// Initialize a new instance of `HttpRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpRequest().with { $0.url = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case url = "url"
    case httpMethod = "httpMethod"
    case headers = "headers"
    case body = "body"
    case oauthToken = "oauthToken"
    case oidcToken = "oidcToken"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.url = try container.decode(Swift.String.self, forKey: .url)
    self.httpMethod = try container.decode(HttpMethod.self, forKey: .httpMethod)
    self.headers = try container.decode([Swift.String: Swift.String].self, forKey: .headers)
    self.body = try container.decode(Foundation.Data.self, forKey: .body)

    var authorizationHeader: OneOf_AuthorizationHeader? = nil
    let authorizationHeaderCheckAndSet = {
      if authorizationHeader != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authorizationHeader'"))
      }
      authorizationHeader = $0
    }
    if let oauthToken = try container.decodeIfPresent(OAuthToken?.self, forKey: .oauthToken) {
      try authorizationHeaderCheckAndSet(.oauthToken(oauthToken))
    }
    if let oidcToken = try container.decodeIfPresent(OidcToken?.self, forKey: .oidcToken) {
      try authorizationHeaderCheckAndSet(.oidcToken(oidcToken))
    }
    self.authorizationHeader = authorizationHeader
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.url, forKey: .url)
    try container.encode(self.httpMethod, forKey: .httpMethod)
    try container.encode(self.headers, forKey: .headers)
    try container.encode(self.body, forKey: .body)

    if let choice = self.authorizationHeader {
      switch choice {
      case .oauthToken(let value):
        try container.encode(value, forKey: .oauthToken)
      case .oidcToken(let value):
        try container.encode(value, forKey: .oidcToken)
      }
    }
  }

  /// The mode for generating an `Authorization` header for HTTP requests.
  ///
  /// If specified, all `Authorization` headers in the
  /// [HttpRequest.headers][google.cloud.tasks.v2.HttpRequest.headers] field will
  /// be overridden.
  ///
  /// [google.cloud.tasks.v2.HttpRequest.headers]: <doc:HttpRequest/headers>
  public enum OneOf_AuthorizationHeader: Codable, Equatable, Sendable {
    /// If specified, an
    /// [OAuth token](https://developers.google.com/identity/protocols/OAuth2)
    /// will be generated and attached as an `Authorization` header in the HTTP
    /// request.
    ///
    /// This type of authorization should generally only be used when calling
    /// Google APIs hosted on *.googleapis.com.
    indirect case oauthToken(OAuthToken?)
    /// If specified, an
    /// [OIDC](https://developers.google.com/identity/protocols/OpenIDConnect)
    /// token will be generated and attached as an `Authorization` header in the
    /// HTTP request.
    ///
    /// This type of authorization can be used for many scenarios, including
    /// calling Cloud Run, or endpoints where you intend to validate the token
    /// yourself.
    indirect case oidcToken(OidcToken?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.HttpRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
