// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// HTTP target.
///
/// When specified at the [Queue][google.cloud.tasks.v2.Queue] level, all tasks
/// with [HttpRequest][google.cloud.tasks.v2.HttpRequest] are overridden
/// according to the target.
///
/// [google.cloud.tasks.v2.HttpRequest]: <doc:HttpRequest>
/// [google.cloud.tasks.v2.Queue]: <doc:Queue>
public struct HttpTarget: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// URI override.
  ///
  /// When specified, overrides the execution URI for all the tasks in the queue.
  public var uriOverride: UriOverride? = nil

  /// The HTTP method to use for the request.
  ///
  /// When specified, it overrides
  /// [HttpRequest][google.cloud.tasks.v2.HttpTarget.http_method] for the task.
  /// Note that if the value is set to [HttpMethod][GET] the [HttpRequest][body]
  /// of the task will be ignored at execution time.
  ///
  /// [google.cloud.tasks.v2.HttpTarget.http_method]: <doc:HttpTarget/httpMethod>
  public var httpMethod: HttpMethod = HttpMethod()

  /// HTTP target headers.
  ///
  /// This map contains the header field names and values.
  /// Headers will be set when running the
  /// [CreateTask][google.cloud.tasks.v2.CloudTasks.CreateTask] and/or
  /// [BufferTask][google.cloud.tasks.v2.CloudTasks.BufferTask].
  ///
  /// These headers represent a subset of the headers that will be configured for
  /// the task's HTTP request. Some HTTP request headers will be ignored or
  /// replaced.
  ///
  /// A partial list of headers that will be ignored or replaced is:
  /// * Several predefined headers, prefixed with "X-CloudTasks-", can
  /// be used to define properties of the task.
  /// * Host: This will be computed by Cloud Tasks and derived from
  /// [HttpRequest.url][google.cloud.tasks.v2.Target.HttpRequest.url].
  /// * Content-Length: This will be computed by Cloud Tasks.
  ///
  /// `Content-Type` won't be set by Cloud Tasks. You can explicitly set
  /// `Content-Type` to a media type when the
  ///  [task is created][google.cloud.tasks.v2.CloudTasks.CreateTask].
  ///  For example, `Content-Type` can be set to `"application/octet-stream"` or
  ///  `"application/json"`. The default value is set to `"application/json"`.
  ///
  /// * User-Agent: This will be set to `"Google-Cloud-Tasks"`.
  ///
  /// Headers which can have multiple values (according to RFC2616) can be
  /// specified using comma-separated values.
  ///
  /// The size of the headers must be less than 80KB.
  /// Queue-level headers to override headers of all the tasks in the queue.
  ///
  /// Do not put business sensitive or personally identifying data in the HTTP
  /// Header Override Configuration or other similar fields in accordance with
  /// Section 12 (Resource Fields) of the
  /// [Service Specific Terms](https://cloud.google.com/terms/service-terms).
  ///
  /// [google.cloud.tasks.v2.CloudTasks.CreateTask]: <doc:CloudTasksClient/createTask(request:options:)>
  public var headerOverrides: [HttpTarget.HeaderOverride] = []

  /// The mode for generating an `Authorization` header for HTTP requests.
  ///
  /// If specified, all `Authorization` headers in the
  /// [HttpRequest.headers][google.cloud.tasks.v2.HttpRequest.headers] field are
  /// overridden.
  ///
  /// [google.cloud.tasks.v2.HttpRequest.headers]: <doc:HttpRequest/headers>
  public var authorizationHeader: AuthorizationHeaderOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HttpTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpTarget().with { $0.uriOverride = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uriOverride = CodingKeys(stringValue: "uriOverride")
    static let httpMethod = CodingKeys(stringValue: "httpMethod")
    static let headerOverrides = CodingKeys(stringValue: "headerOverrides")
    static let oauthToken = CodingKeys(stringValue: "oauthToken")
    static let oidcToken = CodingKeys(stringValue: "oidcToken")

    static let _knownKeys: Set<Swift.String> = [
      "uriOverride",
      "httpMethod",
      "headerOverrides",
      "oauthToken",
      "oidcToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.uriOverride = try container.decodeIfPresent(UriOverride.self, forKey: .uriOverride)
    if let value = try container.decodeIfPresent(HttpMethod.self, forKey: .httpMethod) {
      self.httpMethod = value
    }
    if let value = try container.decodeIfPresent(
      [HttpTarget.HeaderOverride].self, forKey: .headerOverrides)
    {
      self.headerOverrides = value
    }

    var authorizationHeader: AuthorizationHeaderOneOf? = nil
    let authorizationHeaderCheckAndSet = {
      if authorizationHeader != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authorizationHeader'"))
      }
      authorizationHeader = $0
    }
    if let oauthToken = try container.decodeIfPresent(OAuthToken.self, forKey: .oauthToken) {
      try authorizationHeaderCheckAndSet(.oauthToken(oauthToken))
    }
    if let oidcToken = try container.decodeIfPresent(OidcToken.self, forKey: .oidcToken) {
      try authorizationHeaderCheckAndSet(.oidcToken(oidcToken))
    }
    self.authorizationHeader = authorizationHeader
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.uriOverride, forKey: .uriOverride)
    try container.encode(self.httpMethod, forKey: .httpMethod)
    try container.encode(self.headerOverrides, forKey: .headerOverrides)

    if let choice = self.authorizationHeader {
      switch choice {
      case .oauthToken(let value):
        try container.encode(value, forKey: .oauthToken)
      case .oidcToken(let value):
        try container.encode(value, forKey: .oidcToken)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Defines a header message. A header can have a key and a value.
  public struct Header: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Key of the header.
    public var key: Swift.String = Swift.String()

    /// The Value of the header.
    public var value: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Header`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Header().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let key = CodingKeys(stringValue: "key")
      static let value = CodingKeys(stringValue: "value")

      static let _knownKeys: Set<Swift.String> = [
        "key",
        "value",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
        self.key = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .value) {
        self.value = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.key, forKey: .key)
      try container.encode(self.value, forKey: .value)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tasks.v2.HttpTarget.Header"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Wraps the Header object.
  public struct HeaderOverride: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Header embodying a key and a value.
    ///
    /// Do not put business sensitive or personally identifying data in the HTTP
    /// Header Override Configuration or other similar fields in accordance with
    /// Section 12 (Resource Fields) of the
    /// [Service Specific Terms](https://cloud.google.com/terms/service-terms).
    public var header: HttpTarget.Header? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `HeaderOverride`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HeaderOverride().with { $0.header = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let header = CodingKeys(stringValue: "header")

      static let _knownKeys: Set<Swift.String> = [
        "header"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.header = try container.decodeIfPresent(HttpTarget.Header.self, forKey: .header)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.header, forKey: .header)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.tasks.v2.HttpTarget.HeaderOverride"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The mode for generating an `Authorization` header for HTTP requests.
  ///
  /// If specified, all `Authorization` headers in the
  /// [HttpRequest.headers][google.cloud.tasks.v2.HttpRequest.headers] field are
  /// overridden.
  ///
  /// [google.cloud.tasks.v2.HttpRequest.headers]: <doc:HttpRequest/headers>
  public enum AuthorizationHeaderOneOf: Codable, Equatable, Sendable {
    /// If specified, an
    /// [OAuth token](https://developers.google.com/identity/protocols/OAuth2)
    /// is generated and attached as the `Authorization` header in the HTTP
    /// request.
    ///
    /// This type of authorization should generally be used only when calling
    /// Google APIs hosted on *.googleapis.com. Note that both the service
    /// account email and the scope MUST be specified when using the queue-level
    /// authorization override.
    indirect case oauthToken(OAuthToken)
    /// If specified, an
    /// [OIDC](https://developers.google.com/identity/protocols/OpenIDConnect)
    /// token is generated and attached as an `Authorization` header in the
    /// HTTP request.
    ///
    /// This type of authorization can be used for many scenarios, including
    /// calling Cloud Run, or endpoints where you intend to validate the token
    /// yourself. Note that both the service account email and the audience MUST
    /// be specified when using the queue-level authorization override.
    indirect case oidcToken(OidcToken)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.HttpTarget"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
