// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [ListQueues][google.cloud.tasks.v2.CloudTasks.ListQueues].
///
/// [google.cloud.tasks.v2.CloudTasks.ListQueues]: <doc:CloudTasksClient/listQueues(request:options:)>
public struct ListQueuesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The location name.
  /// For example: `projects/PROJECT_ID/locations/LOCATION_ID`
  public var parent: Swift.String = Swift.String()

  /// `filter` can be used to specify a subset of queues. Any
  /// [Queue][google.cloud.tasks.v2.Queue] field can be used as a filter and
  /// several operators as supported. For example: `<=, <, >=, >, !=, =, :`. The
  /// filter syntax is the same as described in [Stackdriver's Advanced Logs
  /// Filters](https://cloud.google.com/logging/docs/view/advanced_filters).
  ///
  /// Sample filter "state: PAUSED".
  ///
  /// Note that using filters might cause fewer queues than the
  /// requested page_size to be returned.
  ///
  /// [google.cloud.tasks.v2.Queue]: <doc:Queue>
  public var filter: Swift.String = Swift.String()

  /// Requested page size.
  ///
  /// The maximum page size is 9800. If unspecified, the page size will
  /// be the maximum. Fewer queues than requested might be returned,
  /// even if more queues exist; use the
  /// [next_page_token][google.cloud.tasks.v2.ListQueuesResponse.next_page_token]
  /// in the response to determine if more queues exist.
  ///
  /// [google.cloud.tasks.v2.ListQueuesResponse.next_page_token]: <doc:ListQueuesResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying the page of results to return.
  ///
  /// To request the first page results, page_token must be empty. To
  /// request the next page of results, page_token must be the value of
  /// [next_page_token][google.cloud.tasks.v2.ListQueuesResponse.next_page_token]
  /// returned from the previous call to
  /// [ListQueues][google.cloud.tasks.v2.CloudTasks.ListQueues] method. It is an
  /// error to switch the value of the
  /// [filter][google.cloud.tasks.v2.ListQueuesRequest.filter] while iterating
  /// through pages.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.ListQueues]: <doc:CloudTasksClient/listQueues(request:options:)>
  /// [google.cloud.tasks.v2.ListQueuesRequest.filter]: <doc:ListQueuesRequest/filter>
  /// [google.cloud.tasks.v2.ListQueuesResponse.next_page_token]: <doc:ListQueuesResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListQueuesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListQueuesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.ListQueuesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
