// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for listing tasks using
/// [ListTasks][google.cloud.tasks.v2.CloudTasks.ListTasks].
///
/// [google.cloud.tasks.v2.CloudTasks.ListTasks]: <doc:CloudTasksClient/listTasks(request:options:)>
public struct ListTasksRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The queue name. For example:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID`
  public var parent: Swift.String = Swift.String()

  /// The response_view specifies which subset of the
  /// [Task][google.cloud.tasks.v2.Task] will be returned.
  ///
  /// By default response_view is [BASIC][google.cloud.tasks.v2.Task.View.BASIC];
  /// not all information is retrieved by default because some data, such as
  /// payloads, might be desirable to return only when needed because
  /// of its large size or because of the sensitivity of data that it
  /// contains.
  ///
  /// Authorization for [FULL][google.cloud.tasks.v2.Task.View.FULL] requires
  /// `cloudtasks.tasks.fullView` [Google IAM](https://cloud.google.com/iam/)
  /// permission on the [Task][google.cloud.tasks.v2.Task] resource.
  ///
  /// [google.cloud.tasks.v2.Task]: <doc:Task>
  /// [google.cloud.tasks.v2.Task.View.BASIC]: <doc:Task/View/basic>
  /// [google.cloud.tasks.v2.Task.View.FULL]: <doc:Task/View/full>
  public var responseView: Task.View = Task.View()

  /// Maximum page size.
  ///
  /// Fewer tasks than requested might be returned, even if more tasks exist; use
  /// [next_page_token][google.cloud.tasks.v2.ListTasksResponse.next_page_token]
  /// in the response to determine if more tasks exist.
  ///
  /// The maximum page size is 1000. If unspecified, the page size will be the
  /// maximum.
  ///
  /// [google.cloud.tasks.v2.ListTasksResponse.next_page_token]: <doc:ListTasksResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying the page of results to return.
  ///
  /// To request the first page results, page_token must be empty. To
  /// request the next page of results, page_token must be the value of
  /// [next_page_token][google.cloud.tasks.v2.ListTasksResponse.next_page_token]
  /// returned from the previous call to
  /// [ListTasks][google.cloud.tasks.v2.CloudTasks.ListTasks] method.
  ///
  /// The page token is valid for only 2 hours.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.ListTasks]: <doc:CloudTasksClient/listTasks(request:options:)>
  /// [google.cloud.tasks.v2.ListTasksResponse.next_page_token]: <doc:ListTasksResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListTasksRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTasksRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let responseView = CodingKeys(stringValue: "responseView")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "responseView",
      "pageSize",
      "pageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Task.View.self, forKey: .responseView) {
      self.responseView = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.responseView, forKey: .responseView)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.ListTasksRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
