// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Response message for
/// [ListQueues][google.cloud.tasks.v2.CloudTasks.ListQueues].
///
/// [google.cloud.tasks.v2.CloudTasks.ListQueues]: <doc:CloudTasksClient/listQueues(request:options:)>
public struct ListQueuesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The list of queues.
  public var queues: [Queue] = []

  /// A token to retrieve next page of results.
  ///
  /// To return the next page of results, call
  /// [ListQueues][google.cloud.tasks.v2.CloudTasks.ListQueues] with this value
  /// as the [page_token][google.cloud.tasks.v2.ListQueuesRequest.page_token].
  ///
  /// If the next_page_token is empty, there are no more results.
  ///
  /// The page token is valid for only 2 hours.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.ListQueues]: <doc:CloudTasksClient/listQueues(request:options:)>
  /// [google.cloud.tasks.v2.ListQueuesRequest.page_token]: <doc:ListQueuesRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListQueuesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListQueuesResponse().with { $0.queues = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.ListQueuesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Queue] {
    return self.queues
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
