// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A queue is a container of related tasks. Queues are configured to manage
/// how those tasks are dispatched. Configurable properties include rate limits,
/// retry options, queue types, and others.
public struct Queue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Caller-specified and required in
  /// [CreateQueue][google.cloud.tasks.v2.CloudTasks.CreateQueue], after which it
  /// becomes output only.
  ///
  /// The queue name.
  ///
  /// The queue name must have the following format:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID`
  ///
  /// * `PROJECT_ID` can contain letters ([A-Za-z]), numbers ([0-9]),
  ///    hyphens (-), colons (:), or periods (.).
  ///    For more information, see
  ///    [Identifying
  ///    projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects)
  /// * `LOCATION_ID` is the canonical ID for the queue's location.
  ///    The list of available locations can be obtained by calling
  ///    [ListLocations][google.cloud.location.Locations.ListLocations].
  ///    For more information, see https://cloud.google.com/about/locations/.
  /// * `QUEUE_ID` can contain letters ([A-Za-z]), numbers ([0-9]), or
  ///   hyphens (-). The maximum length is 100 characters.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.CreateQueue]: <doc:CloudTasksClient/createQueue(request:options:)>
  public var name: Swift.String = Swift.String()

  /// Overrides for
  /// [task-level
  /// app_engine_routing][google.cloud.tasks.v2.AppEngineHttpRequest.app_engine_routing].
  /// These settings apply only to
  /// [App Engine tasks][google.cloud.tasks.v2.AppEngineHttpRequest] in this
  /// queue. [Http tasks][google.cloud.tasks.v2.HttpRequest] are not affected.
  ///
  /// If set, `app_engine_routing_override` is used for all
  /// [App Engine tasks][google.cloud.tasks.v2.AppEngineHttpRequest] in the
  /// queue, no matter what the setting is for the [task-level
  /// app_engine_routing][google.cloud.tasks.v2.AppEngineHttpRequest.app_engine_routing].
  ///
  /// [google.cloud.tasks.v2.AppEngineHttpRequest]: <doc:AppEngineHttpRequest>
  /// [google.cloud.tasks.v2.AppEngineHttpRequest.app_engine_routing]: <doc:AppEngineHttpRequest/appEngineRouting>
  /// [google.cloud.tasks.v2.HttpRequest]: <doc:HttpRequest>
  public var appEngineRoutingOverride: AppEngineRouting? = nil

  /// Rate limits for task dispatches.
  ///
  /// [rate_limits][google.cloud.tasks.v2.Queue.rate_limits] and
  /// [retry_config][google.cloud.tasks.v2.Queue.retry_config] are related
  /// because they both control task attempts. However they control task attempts
  /// in different ways:
  ///
  /// * [rate_limits][google.cloud.tasks.v2.Queue.rate_limits] controls the total
  /// rate of
  ///   dispatches from a queue (i.e. all traffic dispatched from the
  ///   queue, regardless of whether the dispatch is from a first
  ///   attempt or a retry).
  /// * [retry_config][google.cloud.tasks.v2.Queue.retry_config] controls what
  /// happens to
  ///   particular a task after its first attempt fails. That is,
  ///   [retry_config][google.cloud.tasks.v2.Queue.retry_config] controls task
  ///   retries (the second attempt, third attempt, etc).
  ///
  /// The queue's actual dispatch rate is the result of:
  ///
  /// * Number of tasks in the queue
  /// * User-specified throttling:
  /// [rate_limits][google.cloud.tasks.v2.Queue.rate_limits],
  ///   [retry_config][google.cloud.tasks.v2.Queue.retry_config], and the
  ///   [queue's state][google.cloud.tasks.v2.Queue.state].
  /// * System throttling due to `429` (Too Many Requests) or `503` (Service
  ///   Unavailable) responses from the worker, high error rates, or to smooth
  ///   sudden large traffic spikes.
  ///
  /// [google.cloud.tasks.v2.Queue.rate_limits]: <doc:Queue/rateLimits>
  /// [google.cloud.tasks.v2.Queue.retry_config]: <doc:Queue/retryConfig>
  /// [google.cloud.tasks.v2.Queue.state]: <doc:Queue/state>
  public var rateLimits: RateLimits? = nil

  /// Settings that determine the retry behavior.
  ///
  /// * For tasks created using Cloud Tasks: the queue-level retry settings
  ///   apply to all tasks in the queue that were created using Cloud Tasks.
  ///   Retry settings cannot be set on individual tasks.
  /// * For tasks created using the App Engine SDK: the queue-level retry
  ///   settings apply to all tasks in the queue which do not have retry settings
  ///   explicitly set on the task and were created by the App Engine SDK. See
  ///   [App Engine
  ///   documentation](https://cloud.google.com/appengine/docs/standard/python/taskqueue/push/retrying-tasks).
  public var retryConfig: RetryConfig? = nil

  /// Output only. The state of the queue.
  ///
  /// `state` can only be changed by calling
  /// [PauseQueue][google.cloud.tasks.v2.CloudTasks.PauseQueue],
  /// [ResumeQueue][google.cloud.tasks.v2.CloudTasks.ResumeQueue], or uploading
  /// [queue.yaml/xml](https://cloud.google.com/appengine/docs/python/config/queueref).
  /// [UpdateQueue][google.cloud.tasks.v2.CloudTasks.UpdateQueue] cannot be used
  /// to change `state`.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.PauseQueue]: <doc:CloudTasksClient/pauseQueue(request:options:)>
  /// [google.cloud.tasks.v2.CloudTasks.ResumeQueue]: <doc:CloudTasksClient/resumeQueue(request:options:)>
  /// [google.cloud.tasks.v2.CloudTasks.UpdateQueue]: <doc:CloudTasksClient/updateQueue(request:options:)>
  public var state: Queue.State = Queue.State()

  /// Output only. The last time this queue was purged.
  ///
  /// All tasks that were [created][google.cloud.tasks.v2.Task.create_time]
  /// before this time were purged.
  ///
  /// A queue can be purged using
  /// [PurgeQueue][google.cloud.tasks.v2.CloudTasks.PurgeQueue], the [App Engine
  /// Task Queue SDK, or the Cloud
  /// Console](https://cloud.google.com/appengine/docs/standard/python/taskqueue/push/deleting-tasks-and-queues#purging_all_tasks_from_a_queue).
  ///
  /// Purge time will be truncated to the nearest microsecond. Purge
  /// time will be unset if the queue has never been purged.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.PurgeQueue]: <doc:CloudTasksClient/purgeQueue(request:options:)>
  /// [google.cloud.tasks.v2.Task.create_time]: <doc:Task/createTime>
  public var purgeTime: GoogleCloudWkt.Timestamp? = nil

  /// Configuration options for writing logs to
  /// [Stackdriver Logging](https://cloud.google.com/logging/docs/). If this
  /// field is unset, then no logs are written.
  public var stackdriverLoggingConfig: StackdriverLoggingConfig? = nil

  /// Initialize a new instance of `Queue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Queue().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the queue.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// The queue is running. Tasks can be dispatched.
    ///
    /// If the queue was created using Cloud Tasks and the queue has
    /// had no activity (method calls or task dispatches) for 30 days,
    /// the queue may take a few minutes to re-activate. Some method
    /// calls may return [NOT_FOUND][google.rpc.Code.NOT_FOUND] and
    /// tasks may not be dispatched for a few minutes until the queue
    /// has been re-activated.
    case running
    /// Tasks are paused by the user. If the queue is paused then Cloud
    /// Tasks will stop delivering tasks from it, but more tasks can
    /// still be added to it by the user.
    case paused
    /// The queue is disabled.
    ///
    /// A queue becomes `DISABLED` when
    /// [queue.yaml](https://cloud.google.com/appengine/docs/python/config/queueref)
    /// or
    /// [queue.xml](https://cloud.google.com/appengine/docs/standard/java/config/queueref)
    /// is uploaded which does not contain the queue. You cannot directly disable
    /// a queue.
    ///
    /// When a queue is disabled, tasks can still be added to a queue
    /// but the tasks are not dispatched.
    ///
    /// To permanently delete this queue and all of its tasks, call
    /// [DeleteQueue][google.cloud.tasks.v2.CloudTasks.DeleteQueue].
    ///
    /// [google.cloud.tasks.v2.CloudTasks.DeleteQueue]: <doc:CloudTasksClient/deleteQueue(request:options:)>
    case disabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .running: return 1
      case .paused: return 2
      case .disabled: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .running: return "RUNNING"
      case .paused: return "PAUSED"
      case .disabled: return "DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RUNNING": self = .running
      case "PAUSED": self = .paused
      case "DISABLED": self = .disabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .running
      case 2: self = .paused
      case 3: self = .disabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .running: return try container.encode(1)
      case .paused: return try container.encode(2)
      case .disabled: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.Queue"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
