// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Retry config.
///
/// These settings determine when a failed task attempt is retried.
public struct RetryConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Number of attempts per task.
  ///
  /// Cloud Tasks will attempt the task `max_attempts` times (that is, if the
  /// first attempt fails, then there will be `max_attempts - 1` retries). Must
  /// be >= -1.
  ///
  /// If unspecified when the queue is created, Cloud Tasks will pick the
  /// default.
  ///
  /// -1 indicates unlimited attempts.
  ///
  /// This field has the same meaning as
  /// [task_retry_limit in
  /// queue.yaml/xml](https://cloud.google.com/appengine/docs/standard/python/config/queueref#retry_parameters).
  public var maxAttempts: Swift.Int32 = Swift.Int32()

  /// If positive, `max_retry_duration` specifies the time limit for
  /// retrying a failed task, measured from when the task was first
  /// attempted. Once `max_retry_duration` time has passed *and* the
  /// task has been attempted
  /// [max_attempts][google.cloud.tasks.v2.RetryConfig.max_attempts] times, no
  /// further attempts will be made and the task will be deleted.
  ///
  /// If zero, then the task age is unlimited.
  ///
  /// If unspecified when the queue is created, Cloud Tasks will pick the
  /// default.
  ///
  ///
  /// `max_retry_duration` will be truncated to the nearest second.
  ///
  /// This field has the same meaning as
  /// [task_age_limit in
  /// queue.yaml/xml](https://cloud.google.com/appengine/docs/standard/python/config/queueref#retry_parameters).
  ///
  /// [google.cloud.tasks.v2.RetryConfig.max_attempts]: <doc:RetryConfig/maxAttempts>
  public var maxRetryDuration: GoogleCloudWkt.Duration? = nil

  /// A task will be [scheduled][google.cloud.tasks.v2.Task.schedule_time] for
  /// retry between [min_backoff][google.cloud.tasks.v2.RetryConfig.min_backoff]
  /// and [max_backoff][google.cloud.tasks.v2.RetryConfig.max_backoff] duration
  /// after it fails, if the queue's
  /// [RetryConfig][google.cloud.tasks.v2.RetryConfig] specifies that the task
  /// should be retried.
  ///
  /// If unspecified when the queue is created, Cloud Tasks will pick the
  /// default.
  ///
  ///
  /// `min_backoff` will be truncated to the nearest second.
  ///
  /// This field has the same meaning as
  /// [min_backoff_seconds in
  /// queue.yaml/xml](https://cloud.google.com/appengine/docs/standard/python/config/queueref#retry_parameters).
  ///
  /// [google.cloud.tasks.v2.RetryConfig]: <doc:RetryConfig>
  /// [google.cloud.tasks.v2.RetryConfig.max_backoff]: <doc:RetryConfig/maxBackoff>
  /// [google.cloud.tasks.v2.RetryConfig.min_backoff]: <doc:RetryConfig/minBackoff>
  /// [google.cloud.tasks.v2.Task.schedule_time]: <doc:Task/scheduleTime>
  public var minBackoff: GoogleCloudWkt.Duration? = nil

  /// A task will be [scheduled][google.cloud.tasks.v2.Task.schedule_time] for
  /// retry between [min_backoff][google.cloud.tasks.v2.RetryConfig.min_backoff]
  /// and [max_backoff][google.cloud.tasks.v2.RetryConfig.max_backoff] duration
  /// after it fails, if the queue's
  /// [RetryConfig][google.cloud.tasks.v2.RetryConfig] specifies that the task
  /// should be retried.
  ///
  /// If unspecified when the queue is created, Cloud Tasks will pick the
  /// default.
  ///
  ///
  /// `max_backoff` will be truncated to the nearest second.
  ///
  /// This field has the same meaning as
  /// [max_backoff_seconds in
  /// queue.yaml/xml](https://cloud.google.com/appengine/docs/standard/python/config/queueref#retry_parameters).
  ///
  /// [google.cloud.tasks.v2.RetryConfig]: <doc:RetryConfig>
  /// [google.cloud.tasks.v2.RetryConfig.max_backoff]: <doc:RetryConfig/maxBackoff>
  /// [google.cloud.tasks.v2.RetryConfig.min_backoff]: <doc:RetryConfig/minBackoff>
  /// [google.cloud.tasks.v2.Task.schedule_time]: <doc:Task/scheduleTime>
  public var maxBackoff: GoogleCloudWkt.Duration? = nil

  /// The time between retries will double `max_doublings` times.
  ///
  /// A task's retry interval starts at
  /// [min_backoff][google.cloud.tasks.v2.RetryConfig.min_backoff], then doubles
  /// `max_doublings` times, then increases linearly, and finally
  /// retries at intervals of
  /// [max_backoff][google.cloud.tasks.v2.RetryConfig.max_backoff] up to
  /// [max_attempts][google.cloud.tasks.v2.RetryConfig.max_attempts] times.
  ///
  /// For example, if
  /// [min_backoff][google.cloud.tasks.v2.RetryConfig.min_backoff] is 10s,
  /// [max_backoff][google.cloud.tasks.v2.RetryConfig.max_backoff] is 300s, and
  /// `max_doublings` is 3, then the a task will first be retried in
  /// 10s. The retry interval will double three times, and then
  /// increase linearly by 2^3 * 10s.  Finally, the task will retry at
  /// intervals of [max_backoff][google.cloud.tasks.v2.RetryConfig.max_backoff]
  /// until the task has been attempted
  /// [max_attempts][google.cloud.tasks.v2.RetryConfig.max_attempts] times. Thus,
  /// the requests will retry at 10s, 20s, 40s, 80s, 160s, 240s, 300s, 300s, ....
  ///
  /// If unspecified when the queue is created, Cloud Tasks will pick the
  /// default.
  ///
  ///
  /// This field has the same meaning as
  /// [max_doublings in
  /// queue.yaml/xml](https://cloud.google.com/appengine/docs/standard/python/config/queueref#retry_parameters).
  ///
  /// [google.cloud.tasks.v2.RetryConfig.max_attempts]: <doc:RetryConfig/maxAttempts>
  /// [google.cloud.tasks.v2.RetryConfig.max_backoff]: <doc:RetryConfig/maxBackoff>
  /// [google.cloud.tasks.v2.RetryConfig.min_backoff]: <doc:RetryConfig/minBackoff>
  public var maxDoublings: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `RetryConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RetryConfig().with { $0.maxAttempts = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.RetryConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
