// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A unit of scheduled work.
public struct Task: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optionally caller-specified in
  /// [CreateTask][google.cloud.tasks.v2.CloudTasks.CreateTask].
  ///
  /// The task name.
  ///
  /// The task name must have the following format:
  /// `projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID/tasks/TASK_ID`
  ///
  /// * `PROJECT_ID` can contain letters ([A-Za-z]), numbers ([0-9]),
  ///    hyphens (-), colons (:), or periods (.).
  ///    For more information, see
  ///    [Identifying
  ///    projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects)
  /// * `LOCATION_ID` is the canonical ID for the task's location.
  ///    The list of available locations can be obtained by calling
  ///    [ListLocations][google.cloud.location.Locations.ListLocations].
  ///    For more information, see https://cloud.google.com/about/locations/.
  /// * `QUEUE_ID` can contain letters ([A-Za-z]), numbers ([0-9]), or
  ///   hyphens (-). The maximum length is 100 characters.
  /// * `TASK_ID` can contain only letters ([A-Za-z]), numbers ([0-9]),
  ///   hyphens (-), or underscores (_). The maximum length is 500 characters.
  ///
  /// [google.cloud.tasks.v2.CloudTasks.CreateTask]: <doc:CloudTasks/createTask(request:)>
  public var name: Swift.String = Swift.String()

  /// The time when the task is scheduled to be attempted or retried.
  ///
  /// `schedule_time` will be truncated to the nearest microsecond.
  public var scheduleTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time that the task was created.
  ///
  /// `create_time` will be truncated to the nearest second.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The deadline for requests sent to the worker. If the worker does not
  /// respond by this deadline then the request is cancelled and the attempt
  /// is marked as a `DEADLINE_EXCEEDED` failure. Cloud Tasks will retry the
  /// task according to the [RetryConfig][google.cloud.tasks.v2.RetryConfig].
  ///
  /// Note that when the request is cancelled, Cloud Tasks will stop listening
  /// for the response, but whether the worker stops processing depends on the
  /// worker. For example, if the worker is stuck, it may not react to cancelled
  /// requests.
  ///
  /// The default and maximum values depend on the type of request:
  ///
  /// * For [HTTP tasks][google.cloud.tasks.v2.HttpRequest], the default is 10
  /// minutes. The deadline
  ///   must be in the interval [15 seconds, 30 minutes].
  ///
  /// * For [App Engine tasks][google.cloud.tasks.v2.AppEngineHttpRequest], 0
  /// indicates that the
  ///   request has the default deadline. The default deadline depends on the
  ///   [scaling
  ///   type](https://cloud.google.com/appengine/docs/standard/go/how-instances-are-managed#instance_scaling)
  ///   of the service: 10 minutes for standard apps with automatic scaling, 24
  ///   hours for standard apps with manual and basic scaling, and 60 minutes for
  ///   flex apps. If the request deadline is set, it must be in the interval [15
  ///   seconds, 24 hours 15 seconds]. Regardless of the task's
  ///   `dispatch_deadline`, the app handler will not run for longer than than
  ///   the service's timeout. We recommend setting the `dispatch_deadline` to
  ///   at most a few seconds more than the app handler's timeout. For more
  ///   information see
  ///   [Timeouts](https://cloud.google.com/tasks/docs/creating-appengine-handlers#timeouts).
  ///
  /// `dispatch_deadline` will be truncated to the nearest millisecond. The
  /// deadline is an approximate deadline.
  ///
  /// [google.cloud.tasks.v2.AppEngineHttpRequest]: <doc:AppEngineHttpRequest>
  /// [google.cloud.tasks.v2.HttpRequest]: <doc:HttpRequest>
  /// [google.cloud.tasks.v2.RetryConfig]: <doc:RetryConfig>
  public var dispatchDeadline: GoogleCloudWkt.Duration? = nil

  /// Output only. The number of attempts dispatched.
  ///
  /// This count includes attempts which have been dispatched but haven't
  /// received a response.
  public var dispatchCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of attempts which have received a response.
  public var responseCount: Swift.Int32 = Swift.Int32()

  /// Output only. The status of the task's first attempt.
  ///
  /// Only [dispatch_time][google.cloud.tasks.v2.Attempt.dispatch_time] will be
  /// set. The other [Attempt][google.cloud.tasks.v2.Attempt] information is not
  /// retained by Cloud Tasks.
  ///
  /// [google.cloud.tasks.v2.Attempt]: <doc:Attempt>
  /// [google.cloud.tasks.v2.Attempt.dispatch_time]: <doc:Attempt/dispatchTime>
  public var firstAttempt: Attempt? = nil

  /// Output only. The status of the task's last attempt.
  public var lastAttempt: Attempt? = nil

  /// Output only. The view specifies which subset of the
  /// [Task][google.cloud.tasks.v2.Task] has been returned.
  ///
  /// [google.cloud.tasks.v2.Task]: <doc:Task>
  public var view: Task.View = Task.View()

  /// Required. The message to send to the worker.
  public var messageType: OneOf_MessageType? = nil

  /// Initialize a new instance of `Task`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Task().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case appEngineHttpRequest = "appEngineHttpRequest"
    case httpRequest = "httpRequest"
    case scheduleTime = "scheduleTime"
    case createTime = "createTime"
    case dispatchDeadline = "dispatchDeadline"
    case dispatchCount = "dispatchCount"
    case responseCount = "responseCount"
    case firstAttempt = "firstAttempt"
    case lastAttempt = "lastAttempt"
    case view = "view"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.scheduleTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .scheduleTime)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.dispatchDeadline = try container.decodeIfPresent(
      GoogleCloudWkt.Duration.self, forKey: .dispatchDeadline)
    self.dispatchCount = try container.decode(Swift.Int32.self, forKey: .dispatchCount)
    self.responseCount = try container.decode(Swift.Int32.self, forKey: .responseCount)
    self.firstAttempt = try container.decodeIfPresent(Attempt.self, forKey: .firstAttempt)
    self.lastAttempt = try container.decodeIfPresent(Attempt.self, forKey: .lastAttempt)
    self.view = try container.decode(Task.View.self, forKey: .view)

    var messageType: OneOf_MessageType? = nil
    let messageTypeCheckAndSet = {
      if messageType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'messageType'"))
      }
      messageType = $0
    }
    if let appEngineHttpRequest = try container.decodeIfPresent(
      AppEngineHttpRequest?.self, forKey: .appEngineHttpRequest)
    {
      try messageTypeCheckAndSet(.appEngineHttpRequest(appEngineHttpRequest))
    }
    if let httpRequest = try container.decodeIfPresent(HttpRequest?.self, forKey: .httpRequest) {
      try messageTypeCheckAndSet(.httpRequest(httpRequest))
    }
    self.messageType = messageType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.scheduleTime, forKey: .scheduleTime)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.dispatchDeadline, forKey: .dispatchDeadline)
    try container.encode(self.dispatchCount, forKey: .dispatchCount)
    try container.encode(self.responseCount, forKey: .responseCount)
    try container.encode(self.firstAttempt, forKey: .firstAttempt)
    try container.encode(self.lastAttempt, forKey: .lastAttempt)
    try container.encode(self.view, forKey: .view)

    if let choice = self.messageType {
      switch choice {
      case .appEngineHttpRequest(let value):
        try container.encode(value, forKey: .appEngineHttpRequest)
      case .httpRequest(let value):
        try container.encode(value, forKey: .httpRequest)
      }
    }
  }

  /// The view specifies a subset of [Task][google.cloud.tasks.v2.Task] data.
  ///
  /// When a task is returned in a response, not all
  /// information is retrieved by default because some data, such as
  /// payloads, might be desirable to return only when needed because
  /// of its large size or because of the sensitivity of data that it
  /// contains.
  ///
  /// [google.cloud.tasks.v2.Task]: <doc:Task>
  public enum View: Codable, Equatable, Sendable {
    /// Unspecified. Defaults to BASIC.
    case unspecified
    /// The basic view omits fields which can be large or can contain
    /// sensitive data.
    ///
    /// This view does not include the
    /// [body in
    /// AppEngineHttpRequest][google.cloud.tasks.v2.AppEngineHttpRequest.body].
    /// Bodies are desirable to return only when needed, because they
    /// can be large and because of the sensitivity of the data that you
    /// choose to store in it.
    ///
    /// [google.cloud.tasks.v2.AppEngineHttpRequest.body]: <doc:AppEngineHttpRequest/body>
    case basic
    /// All information is returned.
    ///
    /// Authorization for [FULL][google.cloud.tasks.v2.Task.View.FULL] requires
    /// `cloudtasks.tasks.fullView` [Google IAM](https://cloud.google.com/iam/)
    /// permission on the [Queue][google.cloud.tasks.v2.Queue] resource.
    ///
    /// [google.cloud.tasks.v2.Queue]: <doc:Queue>
    /// [google.cloud.tasks.v2.Task.View.FULL]: <doc:Task/View/full>
    case full
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .basic: return 1
      case .full: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VIEW_UNSPECIFIED"
      case .basic: return "BASIC"
      case .full: return "FULL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:View/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VIEW_UNSPECIFIED": self = .unspecified
      case "BASIC": self = .basic
      case "FULL": self = .full
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:View/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .basic
      case 2: self = .full
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .basic: return try container.encode(1)
      case .full: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Required. The message to send to the worker.
  public enum OneOf_MessageType: Codable, Equatable, Sendable {
    /// HTTP request that is sent to the App Engine app handler.
    ///
    /// An App Engine task is a task that has
    /// [AppEngineHttpRequest][google.cloud.tasks.v2.AppEngineHttpRequest] set.
    ///
    /// [google.cloud.tasks.v2.AppEngineHttpRequest]: <doc:AppEngineHttpRequest>
    indirect case appEngineHttpRequest(AppEngineHttpRequest?)
    /// HTTP request that is sent to the worker.
    ///
    /// An HTTP task is a task that has
    /// [HttpRequest][google.cloud.tasks.v2.HttpRequest] set.
    ///
    /// [google.cloud.tasks.v2.HttpRequest]: <doc:HttpRequest>
    indirect case httpRequest(HttpRequest?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.Task"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
