// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// URI Override.
///
/// When specified, all the HTTP tasks inside the queue will be partially or
/// fully overridden depending on the configured values.
public struct UriOverride: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Scheme override.
  ///
  /// When specified, the task URI scheme is replaced by the provided value (HTTP
  /// or HTTPS).
  public var scheme: UriOverride.Scheme? = nil

  /// Host override.
  ///
  /// When specified, replaces the host part of the task URL. For example,
  /// if the task URL is "https://www.google.com," and host value is set to
  /// "example.net", the overridden URI will be changed to "https://example.net."
  /// Host value cannot be an empty string (INVALID_ARGUMENT).
  public var host: Swift.String? = nil

  /// Port override.
  ///
  /// When specified, replaces the port part of the task URI. For instance,
  /// for a URI "https://www.example.com/example" and port=123, the overridden
  /// URI becomes "https://www.example.com:123/example". Note that the port value
  /// must be a positive integer. Setting the port to 0 (Zero) clears the URI
  /// port.
  public var port: Swift.Int64? = nil

  /// URI path.
  ///
  /// When specified, replaces the existing path of the task URL. Setting the
  /// path value to an empty string clears the URI path segment.
  public var pathOverride: PathOverride? = nil

  /// URI query.
  ///
  /// When specified, replaces the query part of the task URI. Setting the
  /// query value to an empty string clears the URI query segment.
  public var queryOverride: QueryOverride? = nil

  /// URI Override Enforce Mode
  ///
  /// When specified, determines the Target UriOverride mode. If not specified,
  /// it defaults to ALWAYS.
  public var uriOverrideEnforceMode: UriOverride.UriOverrideEnforceMode =
    UriOverride.UriOverrideEnforceMode()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UriOverride`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UriOverride().with { $0.scheme = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scheme = CodingKeys(stringValue: "scheme")
    static let host = CodingKeys(stringValue: "host")
    static let port = CodingKeys(stringValue: "port")
    static let pathOverride = CodingKeys(stringValue: "pathOverride")
    static let queryOverride = CodingKeys(stringValue: "queryOverride")
    static let uriOverrideEnforceMode = CodingKeys(stringValue: "uriOverrideEnforceMode")

    static let _knownKeys: Set<Swift.String> = [
      "scheme",
      "host",
      "port",
      "pathOverride",
      "queryOverride",
      "uriOverrideEnforceMode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.scheme = try container.decodeIfPresent(UriOverride.Scheme.self, forKey: .scheme)
    self.host = try container.decodeIfPresent(Swift.String.self, forKey: .host)
    self.port = try container.decodeIfPresent(Swift.Int64.self, forKey: .port)
    self.pathOverride = try container.decodeIfPresent(PathOverride.self, forKey: .pathOverride)
    self.queryOverride = try container.decodeIfPresent(QueryOverride.self, forKey: .queryOverride)
    if let value = try container.decodeIfPresent(
      UriOverride.UriOverrideEnforceMode.self, forKey: .uriOverrideEnforceMode)
    {
      self.uriOverrideEnforceMode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.scheme, forKey: .scheme)
    try container.encodeIfPresent(self.host, forKey: .host)
    try container.encodeIfPresent(self.port, forKey: .port)
    try container.encodeIfPresent(self.pathOverride, forKey: .pathOverride)
    try container.encodeIfPresent(self.queryOverride, forKey: .queryOverride)
    try container.encode(self.uriOverrideEnforceMode, forKey: .uriOverrideEnforceMode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The Scheme for an HTTP request. By default, it is HTTPS.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Scheme: Codable, Equatable, Hashable, Sendable {
    /// Scheme unspecified. Defaults to HTTPS.
    case unspecified
    /// Convert the scheme to HTTP, e.g., "https://www.example.com" will change
    /// to "http://www.example.com".
    case http
    /// Convert the scheme to HTTPS, e.g., "http://www.example.com" will change
    /// to "https://www.example.com".
    case https
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .http: return 1
      case .https: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SCHEME_UNSPECIFIED"
      case .http: return "HTTP"
      case .https: return "HTTPS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Scheme/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SCHEME_UNSPECIFIED": self = .unspecified
      case "HTTP": self = .http
      case "HTTPS": self = .https
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Scheme/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .http
      case 2: self = .https
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SCHEME_UNSPECIFIED")
      case .http: return try container.encode("HTTP")
      case .https: return try container.encode("HTTPS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// UriOverrideEnforceMode defines when the URI override is enforced.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum UriOverrideEnforceMode: Codable, Equatable, Hashable, Sendable {
    /// UriOverrideEnforceMode Unspecified. Defaults to ALWAYS.
    case unspecified
    /// In the IF_NOT_EXISTS mode, queue-level configuration is only
    /// applied where task-level configuration does not exist.
    case ifNotExists
    /// In the ALWAYS mode, queue-level configuration overrides all
    /// task-level configuration
    case always
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ifNotExists: return 1
      case .always: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "URI_OVERRIDE_ENFORCE_MODE_UNSPECIFIED"
      case .ifNotExists: return "IF_NOT_EXISTS"
      case .always: return "ALWAYS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UriOverrideEnforceMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "URI_OVERRIDE_ENFORCE_MODE_UNSPECIFIED": self = .unspecified
      case "IF_NOT_EXISTS": self = .ifNotExists
      case "ALWAYS": self = .always
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UriOverrideEnforceMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ifNotExists
      case 2: self = .always
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("URI_OVERRIDE_ENFORCE_MODE_UNSPECIFIED")
      case .ifNotExists: return try container.encode("IF_NOT_EXISTS")
      case .always: return try container.encode("ALWAYS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.tasks.v2.UriOverride"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
